// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var State$AgdaModeVscode = require("./State.bs.js");
var State__Editor$AgdaModeVscode = require("./State__Editor.bs.js");
var State__Connection$AgdaModeVscode = require("./State__Connection.bs.js");
var State__Decoration$AgdaModeVscode = require("./State__Decoration.bs.js");

function Impl(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var DecoM = State__Decoration$AgdaModeVscode.Impl(Editor);
  var ConnM = State__Connection$AgdaModeVscode.Impl(Editor);
  var EditM = State__Editor$AgdaModeVscode.Impl(Editor);
  var handle = function (state, command) {
    if (typeof command === "number" && command === 0) {
      console.log("LOAD");
      return $$Promise.flatMap($$Promise.flatMap($$Promise.flatMap(Curry._1(EditM.saveEditor, state), EditM.saveCursor), DecoM.removeAll), Curry._1(ConnM.sendRequest, /* Load */0));
    } else {
      return $$Promise.resolved(state);
    }
  };
  return {
          State: State,
          DecoM: DecoM,
          ConnM: ConnM,
          EditM: EditM,
          handle: handle
        };
}

var Js$prime;

var Js;

exports.Js$prime = Js$prime;
exports.Js = Js;
exports.Impl = Impl;
/* Promise Not a pure module */
