// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var State$AgdaModeVscode = require("./State.bs.js");
var Parser$AgdaModeVscode = require("../Parser.bs.js");
var Connection$AgdaModeVscode = require("../Connection.bs.js");
var State__View$AgdaModeVscode = require("./State__View.bs.js");

function Impl(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var ViewM = State__View$AgdaModeVscode.Impl(Editor);
  var handle = function (error) {
    if (typeof error === "number") {
      if (error === /* Cancelled */0) {
        return Curry._2(ViewM.displayError, "Query Cancelled", undefined);
      } else {
        return Curry._2(ViewM.displayError, "Out of goal", "Please place the cursor in a goal");
      }
    }
    if (error.tag) {
      var body = Parser$AgdaModeVscode.$$Error.toString(error[0]);
      return Curry._2(ViewM.displayError, "Internal Parse Error", body);
    }
    var match = Connection$AgdaModeVscode.$$Error.toString(error[0]);
    return Curry._2(ViewM.displayError, "Connection Error: " + match[0], match[1]);
  };
  return {
          State: State,
          ViewM: ViewM,
          handle: handle
        };
}

var Js$prime;

var Js;

exports.Js$prime = Js$prime;
exports.Js = Js;
exports.Impl = Impl;
/* State-AgdaModeVscode Not a pure module */
