// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Goal$AgdaModeVscode = require("../Goal.bs.js");
var State$AgdaModeVscode = require("./State.bs.js");

function Impl(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var Goal = Goal$AgdaModeVscode.Impl(Editor);
  var removeAll = function (state) {
    Belt_Array.forEach(state.decorations, Editor.Decoration.destroy);
    state.decorations = [];
    return $$Promise.resolved(state);
  };
  return {
          State: State,
          Goal: Goal,
          removeAll: removeAll
        };
}

var Js$prime;

var Js;

exports.Js$prime = Js$prime;
exports.Js = Js;
exports.Impl = Impl;
/* Promise Not a pure module */
