// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Goal$AgdaModeVscode = require("../Goal.bs.js");
var State$AgdaModeVscode = require("./State.bs.js");
var Decoration$AgdaModeVscode = require("../Decoration.bs.js");

function Impl(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var Goal = Goal$AgdaModeVscode.Impl(Editor);
  var Decoration = Decoration$AgdaModeVscode.Impl(Editor);
  var removeAll = function (state) {
    Belt_Array.forEach(state.decorations, Editor.Decoration.destroy);
    state.decorations = [];
    return $$Promise.resolved(state);
  };
  var add = function (annotations, state) {
    Belt_Array.forEach(annotations, (function (highlighting) {
            var decorations = Curry._2(Decoration.decorateHighlighting, state.editor, highlighting);
            state.decorations = Belt_Array.concat(state.decorations, decorations);
            
          }));
    return $$Promise.resolved(state);
  };
  return {
          State: State,
          Goal: Goal,
          Decoration: Decoration,
          removeAll: removeAll,
          add: add
        };
}

var Js$prime;

var Js;

exports.Js$prime = Js$prime;
exports.Js = Js;
exports.Impl = Impl;
/* Promise Not a pure module */
