// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");

function make(param) {
  return {
          queue: [],
          busy: false
        };
}

function kickStart(self) {
  if (self.busy) {
    return ;
  }
  var task = self.queue.shift();
  if (task !== undefined) {
    self.busy = true;
    return $$Promise.get(Curry._1(task, undefined), (function (param) {
                  self.busy = false;
                  return kickStart(self);
                }));
  }
  
}

function add(self, task) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  var func = function (param) {
    return $$Promise.tap(Curry._1(task, undefined), resolve);
  };
  self.queue.push(func);
  kickStart(self);
  return match[0];
}

exports.make = make;
exports.kickStart = kickStart;
exports.add = add;
/* Promise Not a pure module */
