// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Handle__InputMethod$AgdaModeVscode = require("./Task/Handle__InputMethod.bs.js");

function Impl(Editor) {
  var InputMethodHandler = Handle__InputMethod$AgdaModeVscode.Impl(Editor);
  var handle = function (state, command) {
    if (typeof command === "number" && command === 0) {
      console.log("LOAD");
      return ;
    }
    
  };
  return {
          InputMethodHandler: InputMethodHandler,
          handle: handle
        };
}

exports.Impl = Impl;
/* Handle__InputMethod-AgdaModeVscode Not a pure module */
